temporalio_common.settings:
  type: config_object
  label: 'Temporal.io common settings'
  mapping:
    temporal_url: { type: string, label: 'Temporal UI base URL' }
    hmac_secret:      { type: string, label: 'HMAC secret' }
